/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package engineer;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Jamil
 */
public class addProject extends javax.swing.JInternalFrame {

    /**
     * Creates new form addProject
     */
    public addProject() {
        initComponents();
        Show_Project();
    }
public Connection getConnection(){
    Connection con= null;
        try {
            con = DriverManager.getConnection("jdbc:mysql://localhost/engineer","root","");
            JOptionPane.showMessageDialog(null, "Connected");
         return con;
        } catch (SQLException ex) {
            Logger.getLogger(addProject.class.getName()).log(Level.SEVERE, null, ex);
             return con;
        }
           
}

   public ArrayList<addProjectclass> getProjectList(){
         ArrayList<addProjectclass> projectList = new ArrayList<addProjectclass>();
         Connection con = getConnection();
     String query = "SELECT * FROM projects";
     Statement st;
     ResultSet rs;
     
     
        try {
            st = con.createStatement();
            rs = st.executeQuery(query);
            addProjectclass addprojectclass;
            
            while(rs.next()){
               addprojectclass = new addProjectclass(rs.getInt("id"), rs.getString("DOA"), rs.getString("date"),rs.getString("approval"),rs.getString("CIN"), rs.getString("NOP"), rs.getString("SOF"),rs.getString("location"), rs.getString("subject"), rs.getString("ContractID"), rs.getString("DE") ,rs.getString("ADE"),rs.getString("CCS"),rs.getString("PE"),rs.getString("PI"), rs.getString("OC"), rs.getString("contractor"), rs.getString("CN"),rs.getString("CA"));
               projectList.add(addprojectclass);
            }
            
        } catch (SQLException ex) {
            Logger.getLogger(insertProject.class.getName()).log(Level.SEVERE, null, ex);
        }
     
     return projectList;
        }
        
        public void Show_Project(){
            ArrayList<addProjectclass> list = getProjectList();
            DefaultTableModel model  = (DefaultTableModel)jTable1.getModel();
            
            Object[] row = new Object[18];
            for(int i=0; i < list.size(); i++)
            {
                row[0] = list.get(i).getId();
                row[1] = list.get(i).getDOA();
                row[2] = list.get(i).getDate();
                row[3] = list.get(i).getApproval();
                row[4] = list.get(i).getCIN();
                row[5] = list.get(i).getNOP();
                row[6] = list.get(i).getSOF();
                row[7] = list.get(i).getLocation();
                row[8] = list.get(i).getSubject();
                row[9] = list.get(i).getContractID();
                row[10] = list.get(i).getDE();
                row[11] = list.get(i).getADE();
                row[12] = list.get(i).getCCS();
                row[13] = list.get(i).getPE();
                row[14] = list.get(i).getPI();
                row[15] = list.get(i).getOC();
                row[16] = list.get(i).getContractor();
                row[17] = list.get(i).getCN();
                
                model.addRow(row);
            }
        }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        jPanel1.setBackground(new java.awt.Color(61, 72, 85));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(61, 72, 85));
        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/icons8_Add_50px.png"))); // NOI18N
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel1MouseClicked(evt);
            }
        });

        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/icons8_Add_User_Male_50px.png"))); // NOI18N

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(227, 227, 227)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(148, 148, 148)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(341, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 56, Short.MAX_VALUE)
            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 850, 60));

        jScrollPane1.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_ALWAYS);
        jScrollPane1.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "District Office Address", "Date", "Approval", "Contract I.D. No.", "Name of Project", "Source of fund", "Location", "Subject", "Contract ID w/ Name", "District Engineer", "OIC- Assistant District Engineer", "Chief, Construction  Section", "Project Engineer", "Project Inspector", "Office Code", "Contractor ", "Contractor Name", "Contractor Address"
            }
        ));
        jTable1.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_OFF);
        jTable1.setAutoscrolls(false);
        jTable1.setGridColor(new java.awt.Color(0, 0, 0));
        jTable1.setPreferredSize(new java.awt.Dimension(2500, 64));
        jTable1.setSelectionBackground(new java.awt.Color(61, 72, 85));
        jScrollPane1.setViewportView(jTable1);
        jTable1.getAccessibleContext().setAccessibleDescription("");
        jTable1.getAccessibleContext().setAccessibleParent(jTable1);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, 850, 370));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 491, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseClicked
       new insertProject().setVisible(true);
    }//GEN-LAST:event_jLabel1MouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
